import { CheckCircle2, AlertCircle } from 'lucide-react';

export default function DecisionExplanation({ reasons = [], decision = 'Approved' }) {
  const isPositive = decision === 'Approved';
  return (
    <div className="card card-pad">
      <h3 style={{ fontSize: 15, marginBottom: 4 }}>Why this decision?</h3>
      <p className="text-muted" style={{ fontSize: 13, marginBottom: 12 }}>
        These factors, generated by the risk model, drove the outcome above.
      </p>
      <ul className="reason-list">
        {reasons.map((reason) => (
          <li key={reason}>
            {isPositive ? (
              <CheckCircle2 size={17} color="var(--color-success-600)" style={{ flexShrink: 0, marginTop: 1 }} />
            ) : (
              <AlertCircle size={17} color="var(--color-danger-600)" style={{ flexShrink: 0, marginTop: 1 }} />
            )}
            <span>{reason}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
